// Static methodology + disclaimer shown after the Appendix in the exported PDF (its own
// page) and the public read-only view. Hand-written (not AI-generated), so it is not itself
// subject to hallucination, and it describes the actual guardrails in the data model and
// prompts. One source of truth; `variant` switches between the print and screen class sets.

function DisclaimerBody() {
  return (
    <>
      <p>
        This report&apos;s narrative was generated by Claude Sonnet 4.6 (claude-sonnet-4-6). Like any
        AI-written analysis, it may contain inaccuracies, mischaracterizations, or overstated
        confidence, and it should be read as orientation, not proof. Verify anything you intend to
        rely on against the linked primary sources.
      </p>
      <p>That said, the tool is deliberately built to keep the model on a short leash. Here is how:</p>
      <ul>
        <li>
          <strong>The numbers are computed in code, not by the model.</strong> Every statistic in this
          report (the discovery-pipeline funnel of candidates, approvals, drafts, and publications,
          plus the rates between them; signal counts; and how many developments touch each claim) is
          calculated deterministically from the database. The model is told to use only the figures it
          is given and never to fabricate a count.
        </li>
        <li>
          <strong>It can only describe developments that actually exist.</strong> The narrative is
          grounded solely in signals a human reviewed and published to the Signal Board, together with
          the discovery pipeline&apos;s recorded candidates. The model receives the real developments,
          their sources, and the claims they bear on, and is instructed never to invent a development,
          a number, a URL, or a link that is not in that supplied data.
        </li>
        <li>
          <strong>Generation is offline and structured.</strong> The model writes from the provided,
          vetted data through a single forced-tool call with web search disabled, so it cannot pull in
          or hallucinate live web content while writing. The work is split into one tightly scoped pass
          per lens plus a synthesis pass, which limits drift and cross-contamination between topics.
        </li>
        <li>
          <strong>Everything is built to be verified.</strong> Every source is a clickable link, and
          every claim and bridge-claim is described in plain language, tagged with its index, and
          linked to its page in the Argument Map (see the Appendix). The claims referenced are resolved
          against the live map, not conjured.
        </li>
        <li>
          <strong>A human is in the loop.</strong> The Atlas runs on a simple principle: the model
          proposes and the human commits. The underlying signals are human-published, and the
          report&apos;s author can review and edit every section, and revise or remove the callouts,
          before saving and sharing it.
        </li>
      </ul>
      <p>
        <strong>Honest limitations.</strong> The guardrails constrain the facts, but the interpretation
        (the framing, the emphasis, the bottom lines, and any inference) is the model&apos;s, and it can
        still be wrong. The signals themselves are summaries of their sources and inherit any error in
        those sources, and the corpus is a curated sample of developments rather than an exhaustive
        record. None of this is investment advice.
      </p>
      <p>
        <strong>Found something off?</strong> Follow the source links to check it, and if you spot an
        inaccuracy, contact the administrator so it can be corrected.
      </p>
    </>
  );
}

export default function ReportDisclaimer({ variant }: { variant: 'print' | 'screen' }) {
  if (variant === 'print') {
    return (
      <section className="print-section print-page">
        <h2 className="print-h">Methodology &amp; Disclaimer</h2>
        <div className="print-body"><DisclaimerBody /></div>
      </section>
    );
  }
  return (
    <section style={{ marginTop: 24 }}>
      <div className="section-label">Methodology &amp; Disclaimer</div>
      <div className="report-prose"><DisclaimerBody /></div>
    </section>
  );
}
