// GENERATED by scripts/author-run.mjs. Do not edit by hand; edit the spec and regenerate.
//
// Token ids and splits are real, produced by a byte-pair tokenizer. Probabilities,
// attention weights, and notes are hand-authored to be representative.

import type { ScriptedRun } from '../run-types';

export const RUN: ScriptedRun = {
  id: "capital-of-france",
  title: "A fact the model is sure about",
  teaser: "The capital of France is",
  prompt: "The capital of France is",
  provenance: 'authored',
  sourceNote: "A deliberately easy completion, chosen so the probability panel shows what near certainty looks like.",
  promptTokens: [
    { id: 976, text: "The", display: "The" },
    { id: 9029, text: " capital", display: "·capital" },
    { id: 328, text: " of", display: "·of" },
    { id: 10128, text: " France", display: "·France" },
    { id: 382, text: " is", display: "·is" },
  ],
  outputs: [
    {
      index: 0,
      token: { id: 12650, text: " Paris", display: "·Paris" },
      top: [
        { token: { id: 12650, text: " Paris", display: "·Paris" }, prob: 0.968 },
        { token: { id: 290, text: " the", display: "·the" }, prob: 0.011 },
        { token: { id: 7567, text: " located", display: "·located" }, prob: 0.006 },
        { token: { id: 261, text: " a", display: "·a" }, prob: 0.004 },
        { token: { id: 1954, text: " now", display: "·now" }, prob: 0.002 },
      ],
      attention: { layer: 14, head: 7, weights: [0.02, 0.32, 0.02, 0.62, 0.02] },
      note: "Almost all the probability mass sits on one token. The model has seen this sentence, or something close to it, many times.",
    },
    {
      index: 1,
      token: { id: 11, text: ",", display: "," },
      top: [
        { token: { id: 11, text: ",", display: "," }, prob: 0.412 },
        { token: { id: 13, text: ".", display: "." }, prob: 0.351 },
        { token: { id: 326, text: " and", display: "·and" }, prob: 0.052 },
        { token: { id: 1118, text: " which", display: "·which" }, prob: 0.041 },
        { token: { id: 290, text: " the", display: "·the" }, prob: 0.018 },
      ],
      attention: { layer: 14, head: 7, weights: [0.02, 0.02, 0.02, 0.2714, 0.02, 0.6486] },
      note: "Punctuation is where the model is least certain. Comma and full stop are both defensible, and the choice steers the rest of the sentence.",
    },
    {
      index: 2,
      token: { id: 290, text: " the", display: "·the" },
      top: [
        { token: { id: 290, text: " the", display: "·the" }, prob: 0.298 },
        { token: { id: 261, text: " a", display: "·a" }, prob: 0.211 },
        { token: { id: 10128, text: " France", display: "·France" }, prob: 0.089 },
        { token: { id: 326, text: " and", display: "·and" }, prob: 0.061 },
        { token: { id: 1118, text: " which", display: "·which" }, prob: 0.044 },
      ],
      attention: { layer: 14, head: 7, weights: [0.02, 0.02, 0.02, 0.02, 0.02, 0.5114, 0.3886] },
    },
    {
      index: 3,
      token: { id: 10574, text: " largest", display: "·largest" },
      top: [
        { token: { id: 10574, text: " largest", display: "·largest" }, prob: 0.324 },
        { token: { id: 1645, text: " most", display: "·most" }, prob: 0.187 },
        { token: { id: 9029, text: " capital", display: "·capital" }, prob: 0.093 },
        { token: { id: 4931, text: " country", display: "·country" }, prob: 0.052 },
        { token: { id: 15512, text: " seat", display: "·seat" }, prob: 0.031 },
      ],
      attention: { layer: 14, head: 7, weights: [0.02, 0.02, 0.02, 0.5, 0.02, 0.38, 0.02, 0.02] },
    },
    {
      index: 4,
      token: { id: 5030, text: " city", display: "·city" },
      top: [
        { token: { id: 5030, text: " city", display: "·city" }, prob: 0.771 },
        { token: { id: 326, text: " and", display: "·and" }, prob: 0.062 },
        { token: { id: 19928, text: " urban", display: "·urban" }, prob: 0.041 },
        { token: { id: 85801, text: " metropolitan", display: "·metropolitan" }, prob: 0.028 },
        { token: { id: 328, text: " of", display: "·of" }, prob: 0.019 },
      ],
      attention: { layer: 14, head: 7, weights: [0.02, 0.02, 0.02, 0.02, 0.02, 0.225, 0.02, 0.02, 0.635] },
      note: "Once the previous token was chosen, this one is nearly forced. Each choice narrows the next.",
    },
    {
      index: 5,
      token: { id: 306, text: " in", display: "·in" },
      top: [
        { token: { id: 306, text: " in", display: "·in" }, prob: 0.643 },
        { token: { id: 328, text: " of", display: "·of" }, prob: 0.201 },
        { token: { id: 326, text: " and", display: "·and" }, prob: 0.048 },
        { token: { id: 656, text: " by", display: "·by" }, prob: 0.026 },
        { token: { id: 11, text: ",", display: "," }, prob: 0.021 },
      ],
      attention: { layer: 14, head: 7, weights: [0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.82] },
    },
    {
      index: 6,
      token: { id: 290, text: " the", display: "·the" },
      top: [
        { token: { id: 290, text: " the", display: "·the" }, prob: 0.582 },
        { token: { id: 10128, text: " France", display: "·France" }, prob: 0.279 },
        { token: { id: 6267, text: " Europe", display: "·Europe" }, prob: 0.049 },
        { token: { id: 2973, text: " both", display: "·both" }, prob: 0.017 },
        { token: { id: 29588, text: " western", display: "·western" }, prob: 0.012 },
      ],
      attention: { layer: 14, head: 7, weights: [0.02, 0.02, 0.02, 0.3543, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.4657] },
    },
    {
      index: 7,
      token: { id: 4931, text: " country", display: "·country" },
      top: [
        { token: { id: 4931, text: " country", display: "·country" }, prob: 0.688 },
        { token: { id: 11836, text: " European", display: "·European" }, prob: 0.093 },
        { token: { id: 2375, text: " world", display: "·world" }, prob: 0.071 },
        { token: { id: 10422, text: " nation", display: "·nation" }, prob: 0.052 },
        { token: { id: 7967, text: " region", display: "·region" }, prob: 0.024 },
      ],
      attention: { layer: 14, head: 7, weights: [0.02, 0.02, 0.02, 0.495, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.305] },
      note: "Eight tokens in, and every one of them was chosen the same way: run the whole stack, look at the distribution, pick one, start again.",
    },
  ],
};
