// GENERATED by scripts/author-run.mjs. Do not edit by hand; edit the spec and regenerate.
//
// Token ids and splits are real, produced by a byte-pair tokenizer. Probabilities,
// attention weights, and notes are hand-authored to be representative.

import type { ScriptedRun } from '../run-types';

export const RUN: ScriptedRun = {
  id: "genuinely-uncertain",
  title: "A sentence with no right answer",
  teaser: "The best thing about winter is",
  prompt: "The best thing about winter is",
  provenance: 'authored',
  sourceNote: "Chosen because no continuation is obviously correct. This is what the output head usually looks like, and why sampling matters.",
  promptTokens: [
    { id: 976, text: "The", display: "The" },
    { id: 1636, text: " best", display: "·best" },
    { id: 4435, text: " thing", display: "·thing" },
    { id: 1078, text: " about", display: "·about" },
    { id: 13655, text: " winter", display: "·winter" },
    { id: 382, text: " is", display: "·is" },
  ],
  outputs: [
    {
      index: 0,
      token: { id: 290, text: " the", display: "·the" },
      top: [
        { token: { id: 290, text: " the", display: "·the" }, prob: 0.401 },
        { token: { id: 484, text: " that", display: "·that" }, prob: 0.238 },
        { token: { id: 14705, text: " watching", display: "·watching" }, prob: 0.061 },
        { token: { id: 78034, text: " waking", display: "·waking" }, prob: 0.044 },
        { token: { id: 1495, text: " how", display: "·how" }, prob: 0.039 },
      ],
      attention: { layer: 14, head: 7, weights: [0.02, 0.3133, 0.02, 0.02, 0.02, 0.6067] },
      note: "Nothing here is above forty percent. Five different tokens are all plausible, and a model that always took the top one would sound the same every time.",
    },
    {
      index: 1,
      token: { id: 15095, text: " quiet", display: "·quiet" },
      top: [
        { token: { id: 15095, text: " quiet", display: "·quiet" }, prob: 0.169 },
        { token: { id: 15214, text: " snow", display: "·snow" }, prob: 0.152 },
        { token: { id: 4207, text: " light", display: "·light" }, prob: 0.118 },
        { token: { id: 12146, text: " cold", display: "·cold" }, prob: 0.094 },
        { token: { id: 2006, text: " way", display: "·way" }, prob: 0.087 },
      ],
      attention: { layer: 14, head: 7, weights: [0.02, 0.02, 0.02, 0.02, 0.02, 0.45, 0.45] },
      note: "The flattest distribution in this run. Sampling temperature has real consequences at moments like this one.",
    },
    {
      index: 2,
      token: { id: 13, text: ".", display: "." },
      top: [
        { token: { id: 13, text: ".", display: "." }, prob: 0.221 },
        { token: { id: 11, text: ",", display: "," }, prob: 0.198 },
        { token: { id: 328, text: " of", display: "·of" }, prob: 0.171 },
        { token: { id: 484, text: " that", display: "·that" }, prob: 0.096 },
        { token: { id: 306, text: " in", display: "·in" }, prob: 0.062 },
      ],
      attention: { layer: 14, head: 7, weights: [0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.86] },
    },
    {
      index: 3,
      token: { id: 28997, text: " Everything", display: "·Everything" },
      top: [
        { token: { id: 28997, text: " Everything", display: "·Everything" }, prob: 0.148 },
        { token: { id: 623, text: " The", display: "·The" }, prob: 0.131 },
        { token: { id: 1225, text: " It", display: "·It" }, prob: 0.119 },
        { token: { id: 30926, text: " Snow", display: "·Snow" }, prob: 0.077 },
        { token: { id: 3274, text: " There", display: "·There" }, prob: 0.058 },
      ],
      attention: { layer: 14, head: 7, weights: [0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.43, 0.43] },
    },
    {
      index: 4,
      token: { id: 134494, text: " slows", display: "·slows" },
      top: [
        { token: { id: 134494, text: " slows", display: "·slows" }, prob: 0.212 },
        { token: { id: 382, text: " is", display: "·is" }, prob: 0.164 },
        { token: { id: 8625, text: " gets", display: "·gets" }, prob: 0.108 },
        { token: { id: 16591, text: " feels", display: "·feels" }, prob: 0.096 },
        { token: { id: 8805, text: " goes", display: "·goes" }, prob: 0.071 },
      ],
      attention: { layer: 14, head: 7, weights: [0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.2486, 0.02, 0.5914] },
    },
    {
      index: 5,
      token: { id: 1917, text: " down", display: "·down" },
      top: [
        { token: { id: 1917, text: " down", display: "·down" }, prob: 0.884 },
        { token: { id: 11, text: ",", display: "," }, prob: 0.031 },
        { token: { id: 326, text: " and", display: "·and" }, prob: 0.024 },
        { token: { id: 261, text: " a", display: "·a" }, prob: 0.012 },
        { token: { id: 13, text: ".", display: "." }, prob: 0.009 },
      ],
      attention: { layer: 14, head: 7, weights: [0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.8] },
      note: "And then a near certainty again. Uncertainty is not a property of the model, it is a property of the position it is in.",
    },
    {
      index: 6,
      token: { id: 13, text: ".", display: "." },
      top: [
        { token: { id: 13, text: ".", display: "." }, prob: 0.523 },
        { token: { id: 11, text: ",", display: "," }, prob: 0.211 },
        { token: { id: 261, text: " a", display: "·a" }, prob: 0.081 },
        { token: { id: 395, text: " for", display: "·for" }, prob: 0.054 },
        { token: { id: 4609, text: " until", display: "·until" }, prob: 0.038 },
      ],
      attention: { layer: 14, head: 7, weights: [0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.78] },
    },
  ],
};
