// GENERATED by scripts/author-run.mjs. Do not edit by hand; edit the spec and regenerate.
//
// Token ids and splits are real, produced by a byte-pair tokenizer. Probabilities,
// attention weights, and notes are hand-authored to be representative.

import type { ScriptedRun } from '../run-types';

export const RUN: ScriptedRun = {
  id: "tokenizer-seams",
  title: "Where the tokenizer shows",
  teaser: "Antidisestablishmentarianism is",
  prompt: "Antidisestablishmentarianism is",
  provenance: 'authored',
  sourceNote: "Chosen to show the seams. Common words survive whole; rare ones are cut into fragments the model then has to reassemble.",
  promptTokens: [
    { id: 18071, text: "Ant", display: "Ant" },
    { id: 129901, text: "idis", display: "idis" },
    { id: 376, text: "est", display: "est" },
    { id: 160388, text: "ablishment", display: "ablishment" },
    { id: 21203, text: "arian", display: "arian" },
    { id: 2367, text: "ism", display: "ism" },
    { id: 382, text: " is", display: "·is" },
  ],
  outputs: [
    {
      index: 0,
      token: { id: 261, text: " a", display: "·a" },
      top: [
        { token: { id: 261, text: " a", display: "·a" }, prob: 0.612 },
        { token: { id: 290, text: " the", display: "·the" }, prob: 0.109 },
        { token: { id: 448, text: " an", display: "·an" }, prob: 0.084 },
        { token: { id: 32724, text: " opposition", display: "·opposition" }, prob: 0.049 },
        { token: { id: 1001, text: " one", display: "·one" }, prob: 0.031 },
      ],
      attention: { layer: 14, head: 7, weights: [0.45, 0.02, 0.02, 0.02, 0.02, 0.45, 0.02] },
      note: "Look at the prompt strip. One long word became several fragments, and the model has to work out that they are a single concept.",
    },
    {
      index: 1,
      token: { id: 10480, text: " political", display: "·political" },
      top: [
        { token: { id: 10480, text: " political", display: "·political" }, prob: 0.387 },
        { token: { id: 1701, text: " long", display: "·long" }, prob: 0.142 },
        { token: { id: 2195, text: " word", display: "·word" }, prob: 0.121 },
        { token: { id: 119070, text: " nineteenth", display: "·nineteenth" }, prob: 0.068 },
        { token: { id: 12772, text: " movement", display: "·movement" }, prob: 0.061 },
      ],
      attention: { layer: 14, head: 7, weights: [0.02, 0.44, 0.44, 0.02, 0.02, 0.02, 0.02, 0.02] },
    },
    {
      index: 2,
      token: { id: 4010, text: " position", display: "·position" },
      top: [
        { token: { id: 4010, text: " position", display: "·position" }, prob: 0.264 },
        { token: { id: 12772, text: " movement", display: "·movement" }, prob: 0.229 },
        { token: { id: 30247, text: " philosophy", display: "·philosophy" }, prob: 0.128 },
        { token: { id: 69038, text: " doctrine", display: "·doctrine" }, prob: 0.094 },
        { token: { id: 69411, text: " stance", display: "·stance" }, prob: 0.062 },
      ],
      attention: { layer: 14, head: 7, weights: [0.02, 0.02, 0.2933, 0.02, 0.02, 0.02, 0.5667, 0.02, 0.02] },
    },
    {
      index: 3,
      token: { id: 484, text: " that", display: "·that" },
      top: [
        { token: { id: 484, text: " that", display: "·that" }, prob: 0.541 },
        { token: { id: 71442, text: " opposing", display: "·opposing" }, prob: 0.161 },
        { token: { id: 306, text: " in", display: "·in" }, prob: 0.084 },
        { token: { id: 1118, text: " which", display: "·which" }, prob: 0.079 },
        { token: { id: 11, text: ",", display: "," }, prob: 0.041 },
      ],
      attention: { layer: 14, head: 7, weights: [0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.82, 0.02, 0.02] },
    },
    {
      index: 4,
      token: { id: 147650, text: " rejects", display: "·rejects" },
      top: [
        { token: { id: 147650, text: " rejects", display: "·rejects" }, prob: 0.446 },
        { token: { id: 106151, text: " arose", display: "·arose" }, prob: 0.121 },
        { token: { id: 9742, text: " developed", display: "·developed" }, prob: 0.098 },
        { token: { id: 44410, text: " emerged", display: "·emerged" }, prob: 0.087 },
        { token: { id: 30669, text: " opposed", display: "·opposed" }, prob: 0.064 },
      ],
      attention: { layer: 14, head: 7, weights: [0.5771, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.2429, 0.02, 0.02] },
      note: "The model recovered the meaning from the fragments. It has to, because it never sees the whole word.",
    },
    {
      index: 5,
      token: { id: 290, text: " the", display: "·the" },
      top: [
        { token: { id: 290, text: " the", display: "·the" }, prob: 0.712 },
        { token: { id: 39612, text: " separation", display: "·separation" }, prob: 0.092 },
        { token: { id: 1062, text: " any", display: "·any" }, prob: 0.048 },
        { token: { id: 2608, text: " state", display: "·state" }, prob: 0.031 },
        { token: { id: 28559, text: " removing", display: "·removing" }, prob: 0.022 },
      ],
      attention: { layer: 14, head: 7, weights: [0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.78, 0.02, 0.02] },
    },
  ],
};
