// Authoring-time generator for Traceroute's curated inference runs.
//
//   node scripts/author-run.mjs
//
// Reads the specs at the bottom of this file and writes one .ts module per run into
// lib/traceroute/runs/. Token ids and token splits come from a real byte-pair tokenizer, so
// the part of the walkthrough that claims to be real tokenization actually is. Everything
// else (probabilities, attention weights, editorial notes) is authored here by hand and is
// labelled as such by ScriptedRun.provenance.
//
// This runs at authoring time only. Regenerate and commit the output; the app never calls it.

import { writeFileSync, mkdirSync } from 'node:fs';
// Pinned encoding, matching components/traceroute/InferencePlayer.tsx. Both must agree or
// a reader's own sentence would tokenize to different ids than the curated runs.
import { encode, decode } from 'gpt-tokenizer/encoding/o200k_base';

const OUT_DIR = new URL('../lib/traceroute/runs/', import.meta.url);

function tokenize(text) {
  return encode(text).map((id) => ({ id, text: decode([id]) }));
}

/** One token, tokenized on its own. Emitted tokens must be a single piece to stay honest. */
function singleToken(text) {
  const ids = encode(text);
  if (ids.length !== 1) {
    // Not fatal: real models emit one vocabulary entry at a time, so if a chosen string is
    // multi-token the spec is wrong and should be shortened.
    throw new Error(
      `author-run: "${text}" is ${ids.length} tokens (${ids.map((i) => JSON.stringify(decode([i]))).join(', ')}). Emitted tokens must be exactly one.`
    );
  }
  return { id: ids[0], text: decode([ids[0]]) };
}

/**
 * Build a normalized attention distribution over `n` prior positions, peaked on the given
 * indices. Authored, not measured: the shape is chosen to illustrate what attention does,
 * which is to read heavily from a few earlier positions and lightly from the rest.
 */
function attention(n, peaks, { floor = 0.02 } = {}) {
  const w = new Array(n).fill(floor);
  const mass = 1 - floor * n;
  const share = mass / peaks.reduce((s, p) => s + p.weight, 0);
  for (const p of peaks) {
    if (p.at < 0 || p.at >= n) throw new Error(`author-run: attention peak ${p.at} out of range 0..${n - 1}`);
    w[p.at] += p.weight * share;
  }
  const total = w.reduce((a, b) => a + b, 0);
  return w.map((x) => Number((x / total).toFixed(4)));
}

function tokenLiteral(t) {
  return `{ id: ${t.id}, text: ${JSON.stringify(t.text)}, display: ${JSON.stringify(display(t.text))} }`;
}

function display(text) {
  return text.replace(/ /g, '·').replace(/\n/g, '↵');
}

function emit(spec) {
  const promptTokens = tokenize(spec.prompt);
  let context = promptTokens.length;

  const outputs = spec.steps.map((step, i) => {
    const tok = singleToken(step.text);
    const alts = (step.alts ?? []).map(([text, prob]) => ({ token: singleToken(text), prob }));
    const top = [{ token: tok, prob: step.prob }, ...alts].sort((a, b) => b.prob - a.prob);
    const att = step.peaks ? attention(context, step.peaks) : null;
    context += 1;
    return { index: i, token: tok, top, attention: att, note: step.note, layer: step.layer ?? 14, head: step.head ?? 7 };
  });

  const body = `// GENERATED by scripts/author-run.mjs. Do not edit by hand; edit the spec and regenerate.
//
// Token ids and splits are real, produced by a byte-pair tokenizer. Probabilities,
// attention weights, and notes are hand-authored to be representative.

import type { ScriptedRun } from '../run-types';

export const RUN: ScriptedRun = {
  id: ${JSON.stringify(spec.id)},
  title: ${JSON.stringify(spec.title)},
  teaser: ${JSON.stringify(spec.teaser)},
  prompt: ${JSON.stringify(spec.prompt)},
  provenance: 'authored',
  sourceNote: ${JSON.stringify(spec.sourceNote)},
  promptTokens: [
${promptTokens.map((t) => `    ${tokenLiteral(t)},`).join('\n')}
  ],
  outputs: [
${outputs
  .map(
    (o) => `    {
      index: ${o.index},
      token: ${tokenLiteral(o.token)},
      top: [
${o.top.map((c) => `        { token: ${tokenLiteral(c.token)}, prob: ${c.prob} },`).join('\n')}
      ],${
        o.attention
          ? `
      attention: { layer: ${o.layer}, head: ${o.head}, weights: [${o.attention.join(', ')}] },`
          : ''
      }${o.note ? `\n      note: ${JSON.stringify(o.note)},` : ''}
    },`
  )
  .join('\n')}
  ],
};
`;

  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(new URL(`${spec.id}.ts`, OUT_DIR), body);
  const emitted = outputs.map((o) => o.token.text).join('');
  console.log(
    `  ${spec.id}: ${promptTokens.length} prompt tokens, ${outputs.length} generated -> ${JSON.stringify(emitted)}`
  );
}

// ---------------------------------------------------------------------------
// The specs
// ---------------------------------------------------------------------------

const SPECS = [
  {
    id: 'capital-of-france',
    title: 'A fact the model is sure about',
    teaser: 'The capital of France is',
    prompt: 'The capital of France is',
    sourceNote: 'A deliberately easy completion, chosen so the probability panel shows what near certainty looks like.',
    steps: [
      {
        text: ' Paris',
        prob: 0.968,
        alts: [[' the', 0.011], [' located', 0.006], [' a', 0.004], [' now', 0.002]],
        peaks: [{ at: 3, weight: 6 }, { at: 1, weight: 3 }],
        note: 'Almost all the probability mass sits on one token. The model has seen this sentence, or something close to it, many times.',
      },
      {
        text: ',',
        prob: 0.412,
        alts: [['.', 0.351], [' and', 0.052], [' which', 0.041], [' the', 0.018]],
        peaks: [{ at: 5, weight: 5 }, { at: 3, weight: 2 }],
        note: 'Punctuation is where the model is least certain. Comma and full stop are both defensible, and the choice steers the rest of the sentence.',
      },
      {
        text: ' the',
        prob: 0.298,
        alts: [[' a', 0.211], [' France', 0.089], [' and', 0.061], [' which', 0.044]],
        peaks: [{ at: 5, weight: 4 }, { at: 6, weight: 3 }],
      },
      {
        text: ' largest',
        prob: 0.324,
        alts: [[' most', 0.187], [' capital', 0.093], [' country', 0.052], [' seat', 0.031]],
        peaks: [{ at: 3, weight: 4 }, { at: 5, weight: 3 }],
      },
      {
        text: ' city',
        prob: 0.771,
        alts: [[' and', 0.062], [' urban', 0.041], [' metropolitan', 0.028], [' of', 0.019]],
        peaks: [{ at: 8, weight: 6 }, { at: 5, weight: 2 }],
        note: 'Once the previous token was chosen, this one is nearly forced. Each choice narrows the next.',
      },
      {
        text: ' in',
        prob: 0.643,
        alts: [[' of', 0.201], [' and', 0.048], [' by', 0.026], [',', 0.021]],
        peaks: [{ at: 9, weight: 5 }],
      },
      {
        text: ' the',
        prob: 0.582,
        alts: [[' France', 0.279], [' Europe', 0.049], [' both', 0.017], [' western', 0.012]],
        peaks: [{ at: 10, weight: 4 }, { at: 3, weight: 3 }],
      },
      {
        text: ' country',
        prob: 0.688,
        alts: [[' European', 0.093], [' world', 0.071], [' nation', 0.052], [' region', 0.024]],
        peaks: [{ at: 3, weight: 5 }, { at: 11, weight: 3 }],
        note: 'Eight tokens in, and every one of them was chosen the same way: run the whole stack, look at the distribution, pick one, start again.',
      },
    ],
  },

  {
    id: 'genuinely-uncertain',
    title: 'A sentence with no right answer',
    teaser: 'The best thing about winter is',
    prompt: 'The best thing about winter is',
    sourceNote: 'Chosen because no continuation is obviously correct. This is what the output head usually looks like, and why sampling matters.',
    steps: [
      {
        text: ' the',
        prob: 0.401,
        alts: [[' that', 0.238], [' watching', 0.061], [' waking', 0.044], [' how', 0.039]],
        peaks: [{ at: 5, weight: 4 }, { at: 1, weight: 2 }],
        note: 'Nothing here is above forty percent. Five different tokens are all plausible, and a model that always took the top one would sound the same every time.',
      },
      {
        text: ' quiet',
        prob: 0.169,
        alts: [[' snow', 0.152], [' light', 0.118], [' cold', 0.094], [' way', 0.087]],
        peaks: [{ at: 5, weight: 3 }, { at: 6, weight: 3 }],
        note: 'The flattest distribution in this run. Sampling temperature has real consequences at moments like this one.',
      },
      {
        text: '.',
        prob: 0.221,
        alts: [[',', 0.198], [' of', 0.171], [' that', 0.096], [' in', 0.062]],
        peaks: [{ at: 7, weight: 4 }],
      },
      {
        text: ' Everything',
        prob: 0.148,
        alts: [[' The', 0.131], [' It', 0.119], [' Snow', 0.077], [' There', 0.058]],
        peaks: [{ at: 7, weight: 3 }, { at: 8, weight: 3 }],
      },
      {
        text: ' slows',
        prob: 0.212,
        alts: [[' is', 0.164], [' gets', 0.108], [' feels', 0.096], [' goes', 0.071]],
        peaks: [{ at: 9, weight: 5 }, { at: 7, weight: 2 }],
      },
      {
        text: ' down',
        prob: 0.884,
        alts: [[',', 0.031], [' and', 0.024], [' a', 0.012], ['.', 0.009]],
        peaks: [{ at: 10, weight: 7 }],
        note: 'And then a near certainty again. Uncertainty is not a property of the model, it is a property of the position it is in.',
      },
      {
        text: '.',
        prob: 0.523,
        alts: [[',', 0.211], [' a', 0.081], [' for', 0.054], [' until', 0.038]],
        peaks: [{ at: 11, weight: 4 }],
      },
    ],
  },

  {
    id: 'tokenizer-seams',
    title: 'Where the tokenizer shows',
    teaser: 'Antidisestablishmentarianism is',
    prompt: 'Antidisestablishmentarianism is',
    sourceNote: 'Chosen to show the seams. Common words survive whole; rare ones are cut into fragments the model then has to reassemble.',
    steps: [
      {
        text: ' a',
        prob: 0.612,
        alts: [[' the', 0.109], [' an', 0.084], [' opposition', 0.049], [' one', 0.031]],
        peaks: [{ at: 0, weight: 3 }, { at: 5, weight: 3 }],
        note: 'Look at the prompt strip. One long word became several fragments, and the model has to work out that they are a single concept.',
      },
      {
        text: ' political',
        prob: 0.387,
        alts: [[' long', 0.142], [' word', 0.121], [' nineteenth', 0.068], [' movement', 0.061]],
        peaks: [{ at: 1, weight: 3 }, { at: 2, weight: 3 }],
      },
      {
        text: ' position',
        prob: 0.264,
        alts: [[' movement', 0.229], [' philosophy', 0.128], [' doctrine', 0.094], [' stance', 0.062]],
        peaks: [{ at: 6, weight: 4 }, { at: 2, weight: 2 }],
      },
      {
        text: ' that',
        prob: 0.541,
        alts: [[' opposing', 0.161], [' in', 0.084], [' which', 0.079], [',', 0.041]],
        peaks: [{ at: 7, weight: 5 }],
      },
      {
        text: ' rejects',
        prob: 0.446,
        alts: [[' arose', 0.121], [' developed', 0.098], [' emerged', 0.087], [' opposed', 0.064]],
        peaks: [{ at: 0, weight: 5 }, { at: 8, weight: 2 }],
        note: 'The model recovered the meaning from the fragments. It has to, because it never sees the whole word.',
      },
      {
        text: ' the',
        prob: 0.712,
        alts: [[' separation', 0.092], [' any', 0.048], [' state', 0.031], [' removing', 0.022]],
        peaks: [{ at: 9, weight: 5 }],
      },
    ],
  },
];

console.log('author-run: generating curated runs');
for (const spec of SPECS) emit(spec);
console.log(`author-run: wrote ${SPECS.length} runs to lib/traceroute/runs/`);
