-- 0028 — The labor domain.
--
-- The map's four domains (capability, economics, build_out, market) never covered
-- the labor / knowledge-work side of the AI-economy debate, so labor-lens signals
-- had no claims to touch and thesis reports on hiring/employment ran text-only
-- with no direction data. This adds the enum value; the question-7 scaffolding
-- (question, stances, claims, edges, lens tags) is seeded by scripts/seed-labor.mjs
-- (idempotent, like db:seed:concepts), NOT here: Postgres allows ADD VALUE inside
-- the migration runner's transaction but forbids USING the new value in the same
-- transaction, so content that needs 'labor' must land after this commits.
alter type domain_t add value if not exists 'labor';
